### ISSUE TITLE
i3wm keybind switching freezes cursor

### ISSUE THREAD

**Issue by jonpas** [gnif/LookingGlass#836] opened 2021-09-06 11:38 UTC
Using i3wm, full-screen Looking Glass in workspace 9. Switching via keybinds from workspace 9 to 1 (or any other) and back to 9 causes a cursor freeze, until the cursor is moved off the LG window (eg. to another screen) and back in. Clicking on the workspace icon in the i3bar doesn't cause that, as focus changes during the click.

This started happening at some point just before B4, I haven't updated in a while until last week, but if needed I can give different versions a try. Currently on 5fbb34f8f3bd323cb94b2ac6c84af56e9c10a87f (this is also where the following logs are from).

### Bug Report Required Information

Last line in the client log is printed in red.

```
[I]  62387641766              main.c:1289 | main                           | Looking Glass (B4-556-g5fbb34f8f3)
[I]  62387641783              main.c:1290 | main                           | Locking Method: Atomic
[I]  62387657266           cpuinfo.c:36   | lgDebugCPU                     | CPU Model: AMD Ryzen 7 3700X 8-Core Processor
[I]  62387657270           cpuinfo.c:37   | lgDebugCPU                     | CPU: 8 cores, 16 threads
[I]  62387660922            config.c:478  | config_load                    | Loading config from: /etc/looking-glass-client.ini
[I]  62387668684              main.c:843  | lg_run                         | Using font: /usr/share/fonts/TTF/DejaVuSansMono.ttf
[I]  62387668707           ivshmem.c:128  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
[I]  62387696928               egl.c:246  | egl_initialize                 | Double buffering is off
[I]  62387696939              main.c:810  | tryRenderer                    | Using Renderer: EGL
[I]  62387697968               x11.c:381  | x11Init                        | X11 XInput 2.0 in use
[I]  62387704176               x11.c:1273 | x11GetEGLDisplay               | Using eglGetPlatformDisplayEXT
[I]  62387742513               egl.c:672  | egl_renderStartup              | Multisampling enabled, max samples: 4
[I]  62387743101               egl.c:740  | egl_renderStartup              | Single buffer mode
[I]  62387745902               egl.c:756  | egl_renderStartup              | EGL     : 1.5
[I]  62387745907               egl.c:757  | egl_renderStartup              | Vendor  : AMD
[I]  62387745910               egl.c:758  | egl_renderStartup              | Renderer: Radeon RX550/550 Series (POLARIS12, DRM 3.41.0, 5.13.13-arch1-1, LLVM 12.0.1)
[I]  62387745913               egl.c:759  | egl_renderStartup              | Version : OpenGL ES 3.2 Mesa 21.2.1
[I]  62387745915               egl.c:760  | egl_renderStartup              | EGL APIs: OpenGL OpenGL_ES 
[I]  62387745916               egl.c:761  | egl_renderStartup              | EGL Exts: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_CHROMIUM_sync_control EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_swap_buffers_with_damage EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_KHR_swap_buffers_with_damage EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_NOK_texture_from_pixmap EGL_WL_bind_wayland_display 
[I]  62387745921               egl.c:762  | egl_renderStartup              | GL Exts : GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_OES_viewport_array GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_robustness GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_ANDROID_extension_pack_es31a GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_gpu_shader5 GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_render_snorm GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_norm16 GL_EXT_texture_view GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_image_formats GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_gpu_shader5 GL_OES_primitive_bounding_box GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_texture_view GL_EXT_blend_func_extended GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_clip_cull_distance GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_EXT_window_rectangles GL_MESA_shader_integer_functions GL_EXT_clip_control GL_EXT_color_buffer_half_float GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_texture_compression_bptc GL_KHR_parallel_shader_compile GL_NV_alpha_to_coverage_dither_control GL_AMD_framebuffer_multisample_advanced GL_EXT_EGL_image_storage GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_demote_to_helper_invocation GL_EXT_depth_clamp GL_EXT_texture_query_lod GL_MESA_bgra 
[I]  62387745937               egl.c:813  | egl_renderStartup              | Debug messages disabled, enable with egl:debug=true
[I]  62387832121           eglutil.c:35   | swapWithDamageInit             | Using EGL_KHR_swap_buffers_with_damage
[I]  62388026238              main.c:1153 | lg_run                         | Host ready, reported version: B4-556-g5fbb34f8f3
[I]  62388026252              main.c:1154 | lg_run                         | Starting session
[I]  62388177342              main.c:614  | main_frameThread               | Format: FRAME_TYPE_BGRA 2560x1080 stride:2560 pitch:10240 rotation:0
[E]  62390396961               x11.c:1522 | x11PrintGrabError              | XIGrabDevice failed for pointer dev 2 with 0x4 (GrabFrozen)
```

```
[I]    933810545              time.c:85   | windowsSetTimerResolution      | System timer resolution: 500.0 μs                                                                   ~
[I]    933811415               app.c:542  | app_main                       | Looking Glass Host (B4-556-g5fbb34f8f3)
[I]    933812303           cpuinfo.c:36   | lgDebugCPU                     | CPU Model: AMD Ryzen 7 3700X 8-Core Processor
[I]    933813280           cpuinfo.c:37   | lgDebugCPU                     | CPU: 8 cores, 16 threads
[I]    933814920           ivshmem.c:131  | ivshmemInit                    | IVSHMEM 0* on bus 0x0, device 0x4, function 0x0
[I]    933819711               app.c:559  | app_main                       | IVSHMEM Size     : 32 MiB
[I]    933820463               app.c:560  | app_main                       | IVSHMEM Address  : 0x2CE0000
[I]    933821156               app.c:561  | app_main                       | Max Pointer Size : 1024 KiB
[I]    933821849               app.c:562  | app_main                       | KVMFR Version    : 14
[I]    933822725               app.c:623  | app_main                       | Max Frame Size   : 14 MiB
[I]    933823714               app.c:648  | app_main                       | Trying           : DXGI
[I]    933827009              dxgi.c:322  | dxgi_init                      | Device Name      : \\.\DISPLAY1
[I]    933827373              dxgi.c:323  | dxgi_init                      | Device Descripion: NVIDIA GeForce GTX 1060 6GB
[I]    933827766              dxgi.c:324  | dxgi_init                      | Device Vendor ID : 0x10de
[I]    933828073              dxgi.c:325  | dxgi_init                      | Device Device ID : 0x1c03
[I]    933828395              dxgi.c:326  | dxgi_init                      | Device Video Mem : 6052 MiB
[I]    933828707              dxgi.c:327  | dxgi_init                      | Device Sys Mem   : 0 MiB
[I]    933829015              dxgi.c:328  | dxgi_init                      | Shared Sys Mem   : 16381 MiB
[I]    933904626              dxgi.c:435  | dxgi_init                      | Feature Level    : 0xc100
[I]    933904956              dxgi.c:436  | dxgi_init                      | Capture Size     : 2560 x 1080
[I]    933905279              dxgi.c:437  | dxgi_init                      | AcquireLock      : enabled
[I]    933906340              dxgi.c:527  | dxgi_init                      | Source Format    : DXGI_FORMAT_B8G8R8A8_UNORM
[I]    933907256               app.c:673  | app_main                       | Using            : DXGI
[I]    933907673               app.c:674  | app_main                       | Capture Method   : Asynchronous
[I]    933908024               app.c:348  | captureStart                   | ==== [ Capture Start ] ====
[I]    933908447               app.c:288  | frameThread                    | Frame thread started
[I]   1003134544               app.c:795  | app_main                       | No subscribers, going to sleep...
[I]   1003821750               app.c:295  | frameThread                    | Frame thread stopped
[I]   1003822621               app.c:354  | captureStop                    | ==== [ Capture Stop ] ====
[I]   1003835722              dxgi.c:322  | dxgi_init                      | Device Name      : \\.\DISPLAY1
[I]   1003836494              dxgi.c:323  | dxgi_init                      | Device Descripion: NVIDIA GeForce GTX 1060 6GB
[I]   1003837278              dxgi.c:324  | dxgi_init                      | Device Vendor ID : 0x10de
[I]   1003837930              dxgi.c:325  | dxgi_init                      | Device Device ID : 0x1c03
[I]   1003838631              dxgi.c:326  | dxgi_init                      | Device Video Mem : 6052 MiB
[I]   1003839285              dxgi.c:327  | dxgi_init                      | Device Sys Mem   : 0 MiB
[I]   1003839955              dxgi.c:328  | dxgi_init                      | Shared Sys Mem   : 16381 MiB
[I]   1003910407              dxgi.c:435  | dxgi_init                      | Feature Level    : 0xc100
[I]   1003910733              dxgi.c:436  | dxgi_init                      | Capture Size     : 2560 x 1080
[I]   1003911088              dxgi.c:437  | dxgi_init                      | AcquireLock      : enabled
[I]   1003912088              dxgi.c:527  | dxgi_init                      | Source Format    : DXGI_FORMAT_B8G8R8A8_UNORM
```

**Comment by gnif** [comment] 2021-09-06 11:50
Unable to reproduce, this is exactly how I use LG also and I have never had this behavior.

Please provide step by step instructions to reproduce, eg:

1. Run the LG client
2. Move to workspace N
3. Something else.

**Comment by jonpas** [comment] 2021-09-06 12:18
1. [Workspace 9] Open LG client (via terminal or dmenu)
2. Set LG client to full-screen
3. Switch to workspace 1 using Mod+1 in i3wm
4. Switch to workspace 9 using Mod+9 in i3wm
5. Observe stuck cursor, as well as a little square artifact from the LG client window before the full window appears.

There is actually no need to set LG client to full-screen. As long as the mouse is grabbed in the window (as in clicked inside in the VM), switching workspaces causes this for me.

To solve it I either:
1. Click the i3bar menu instead, which successfully grabs the mouse afterwards
2. Move the mouse out of LG client window and back in, which successfully grabs the mouse

This is the LG client config I use:
```
[win]
quickSplash=yes

[input]
grabKeyboardOnFocus=no
ignoreWindowsKeys=yes
rawMouse=yes  # capture mode only

[spice]
host=/run/user/1000/spice.sock
port=0
alwaysShowCursor=yes
```
I've also tried without certain options to no effect.

**Comment by jonpas** [comment] 2021-12-14 10:21
Confirmed still present issue in B5-rc1.

Any more information or testing I can provide on this?

**Comment by gnif** [comment] 2021-12-14 10:25
What you have provided is sufficient thanks, I just replicated this and will see what I can do. I simply forgot about this issue before tagging RC1, which is fine, it's the entire point of RCs :)

**Comment by jonpas** [comment] 2021-12-14 10:34
Nice! :+1:

**Comment by gnif** [comment] 2021-12-14 10:56
Can you please test the following patch:
```
diff --git a/client/displayservers/X11/x11.c b/client/displayservers/X11/x11.c
index 18ae239..0e8746d 100644
--- a/client/displayservers/X11/x11.c
+++ b/client/displayservers/X11/x11.c
@@ -82,6 +82,7 @@ static void x11SetFullscreen(bool fs);
 static int  x11EventThread(void * unused);
 static void x11XInputEvent(XGenericEventCookie *cookie);
 static void x11XPresentEvent(XGenericEventCookie *cookie);
+static void x11GrabPointer(void);
 
 static void x11DoPresent(void)
 {
@@ -744,6 +745,16 @@ static int x11EventThread(void * unused)
     {
       x11.invalidateAll = false;
       app_invalidateWindow(true);
+
+      if (x11.deferGrab)
+      {
+        x11.deferGrab = false;
+        if (x11.grabPending)
+        {
+          x11.grabPending = false;
+          x11GrabPointer();
+        }
+      }
     }
 
     if (!XPending(x11.display))
@@ -815,6 +826,8 @@ static int x11EventThread(void * unused)
 
       case Expose:
       {
+        x11.deferGrab = true;
+
         atomic_store(&x11.lastWMEvent, microtime());
         x11.invalidateAll = true;
         break;
@@ -849,6 +862,13 @@ static int x11EventThread(void * unused)
         {
           atomic_store(&x11.lastWMEvent, microtime());
 
+          if (x11.grabPending)
+          {
+            x11.deferGrab   = false;
+            x11.grabPending = false;
+            x11GrabPointer();
+          }
+
           Atom type;
           int fmt;
           unsigned long num, bytes;
@@ -1542,6 +1562,16 @@ static void x11GrabPointer(void)
   if (x11.pointerGrabbed)
     return;
 
+  /* on i3wm if we attempt to grab the pointer immediately when switching
+   * to the workspace with LG on it there is a race that results in a
+   * GrabFrozen error, so defer the grab until either the WM timeout
+   * occurs, or we get a _NET_WM_STATE message */
+  if (x11.deferGrab)
+  {
+    x11.grabPending = true;
+    return;
+  }
+
   unsigned char mask_bits[XIMaskLen(XI_LASTEVENT)] = { 0 };
   XIEventMask mask = {
     x11.pointerDev,
diff --git a/client/displayservers/X11/x11.h b/client/displayservers/X11/x11.h
index 5f339d6..feb4222 100644
--- a/client/displayservers/X11/x11.h
+++ b/client/displayservers/X11/x11.h
@@ -56,6 +56,7 @@ struct X11DSState
 
   _Atomic(uint64_t) lastWMEvent;
   bool              invalidateAll;
+  bool              deferGrab, grabPending;
 
   int               xpresentOp;
   bool              jitRender;
```

**Comment by gnif** [comment] 2021-12-14 11:19
Seems the patch provided is unreliable, still working on the issue.

**Comment by jonpas** [comment] 2021-12-14 11:50
Much better than before, but doesn't seem to be fully reliable yet.

If the mouse is moving, it works consistently (with the exception of the small as artifact as described previously, and a small sync jump).

I can still get it stuck most of the time if switching to workspace while cursor is not moving, with the same error:
```
XIGrabDevice failed for pointer dev 2 with 0x4 (GrabFrozen)
```

**Comment by gnif** [comment] 2021-12-14 13:27
As much as I hate the fix I just pushed in I can't find any alternative to it at current. It does seem to however resolve the issue completely for me. Can you please update and test to see if this has resolved your issue also?

**Comment by jonpas** [comment] 2021-12-14 13:47
It works better.

There is still an edge case, it seems to be something like this:
- Switch to LG workspace
- Switch back and **don't move the mouse**
- Switch back to LG workspace and observe cursor freeze (until move out etc.)

Not 100% reproducible, but most of the time.

However, this is a smaller problem and as much as I don't like waits like that in code, it does solve the bigger issue at hand. Thank you!

**Comment by gnif** [comment] 2021-12-21 10:23
After digging through the i3 source I believe I have found the issue and a fix, can you please test the following patch:

```diff
diff --git a/client/displayservers/X11/x11.c b/client/displayservers/X11/x11.c
index 956a2db5..02f0e24c 100644
--- a/client/displayservers/X11/x11.c
+++ b/client/displayservers/X11/x11.c
@@ -258,7 +258,7 @@ static bool x11Init(const LG_DSInitParams params)
       PropertyChangeMask |
       ExposureMask
   };
-  unsigned long swaMask = CWEventMask;
+  unsigned long swaMask = CWEventMask | CWOverrideRedirect;
 
 #ifdef ENABLE_OPENGL
   if (params.opengl)
```

Note that this may affect how i3 treats the window in general, please be thorough and ensure everything is functional, not just the bug fixed.

**Comment by gnif** [comment] 2021-12-21 10:28
Scratch that sorry, this doesn't work sorry. Still investigating.

**Comment by gnif** [comment] 2021-12-21 10:56
Can you please confirm if 65948034 has fixed this?

**Comment by jonpas** [comment] 2021-12-21 11:39
That seems to work great! Tested for a few minutes and the issue seems to be resolved.

I will do more testing as I use it over the day today and will report back at the end.

**Comment by jonpas** [comment] 2021-12-22 00:04
No issue noticed so far!

**Comment by gnif** [comment] 2021-12-22 00:12
Awesome, closing as fixed but will re-open if this issue is reported again.

**Closed by gnif** 2021-12-22 00:12 UTC
