### ISSUE TITLE
Windows build classified as malware

### ISSUE THREAD

**Issue by epsilontheta** [gnif/LookingGlass#326] opened 2020-11-27 20:26 UTC
The current bleeding edge windows build (Commit: db51acdd) is classified as malware / suspicious by > 50% of the antivirus scanners of virustotal (see [here](https://www.virustotal.com/gui/file/c1210763a7aeddb38525eef5feeb5c8850e3dd58da699411008b7f57c6a0f8cb/detection)).

Any idea what the problem is?
I know.. it's mostly snake oil, but the sheer number of red flags makes me wonder if there is a problem?

**Comment by mjarkk** [comment] 2020-11-27 20:35
I think this is a duplicate of https://github.com/gnif/LookingGlass/issues/285

**Comment by gnif** [comment] 2020-11-27 21:22
Duplicate of #285

**Closed by gnif** 2020-11-27 21:22 UTC
