### ISSUE TITLE
c-host exits/crashes when guest suspends to ram

### ISSUE THREAD

**Issue by tadly** [gnif/LookingGlass#166] opened 2019-06-02 07:08 UTC
### Required information

Host CPU: i7-6700
Host GPU: i7-6700 (HD 530)
Guest GPU: GTX 1660 TI
Host Kernel version: 4.14
Host QEMU version: 4.0

I'm using suspend to ram (which works great) but the c-host seems to die whenever I suspend/resume the guest.
IIRC the original host would create a crash-dump file in the directory but the c-host doesn't so I'm not sure how to provide you any valuable information as of right now.

Let me know if there's anything I can do to debug this.

**Comment by gnif** [comment] 2019-06-02 07:09
Duplicate of #66

**Closed by gnif** 2019-06-02 07:09 UTC
