### ISSUE TITLE
Looking-Glass-Client stopps when pressing any key 

### ISSUE THREAD

**Issue by caHocke** [gnif/LookingGlass#57] opened 2018-04-07 11:54 UTC
### Required information

Host CPU: core-i7 4770
Host GPU: intel-hd graphics
Guest GPU: Nvidia G-Force 780-ti
Host Kernel version: Linux 4.15.15-1-ARCH #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018
Host QEMU version: qemu 2.11.1-2

Problem:
As soon as I press any Key on the Keyboard or the Mouse, the Looking-Glass-Client stops responding and is not updating the conted of the window anymore. It worked until I did the Arch Systemupgrade an hour ago. The Problem also occours when I disable the spice-client.

edit: 
output from:  looking-glass-client -f /dev/shm/looking-glass -c localhost -p 20001 -F

[I]               main.c:680  | run                            | Looking Glass (a10-50-gfd8d4d3d38)
[I]               main.c:681  | run                            | Locking Method: Atomic
[I]               main.c:674  | try_renderer                   | Using Renderer: OpenGL
[I]               main.c:762  | run                            | Using: OpenGL
[I]               main.c:877  | run                            | Waiting for host to signal it's ready...
[I]              spice.c:347  | spice_on_common_read           | notify message: keyboard channel is insecure
[I]               main.c:881  | run                            | Host ready, starting session
[I]               main.c:172  | updatePositionInfo             | client 1680x1050, guest 1680x1050, target 1680x1050, scaleX: 1.00, scaleY 1.00
[I]               main.c:172  | updatePositionInfo             | client 1674x1028, guest 1680x1050, target 1644x1028, scaleX: 1.02, scaleY 1.02
[W]               main.c:175  | updatePositionInfo             | Window size doesn't match guest resolution, cursor alignment may not be reliable
[I]               main.c:172  | updatePositionInfo             | client 1680x1050, guest 1680x1050, target 1680x1050, scaleX: 1.00, scaleY 1.00
[I]             opengl.c:542  | configure                      | Vendor  : Intel Open Source Technology Center
[I]             opengl.c:543  | configure                      | Renderer: Mesa DRI Intel(R) Haswell Desktop 
[I]             opengl.c:544  | configure                      | Version : 3.0 Mesa 18.0.0
[I]             opengl.c:575  | configure                      | Using decoder: NULL
[I]               main.c:172  | updatePositionInfo             | client 1680x1050, guest 1680x1050, target 1680x1050, scaleX: 1.00, scaleY 1.00

I don't think it sad decoder: NULL befor but I am not sure

**Comment by icewind1991** [comment] 2018-04-07 13:15
Looks like a duplicate of https://github.com/gnif/LookingGlass/issues/53

**Comment by gnif** [comment] 2018-04-09 10:18
Please use a tagged release, you are using the experimental version with initial decoder support which is completely unsupported.

**Comment by caHocke** [comment] 2018-04-09 10:44
Icewind was right it is a duplicate downgrading Mesa fixed my issue

**Closed** 2018-04-09 10:44 UTC
