### ISSUE TITLE
Inconsistencies with guest mouse cursor on multi-monitor setup

### ISSUE THREAD

**Issue by mcd1992** [gnif/LookingGlass#17] opened 2017-12-15 04:58 UTC
### Required information

Host CPU: i7-5930K
Host GPU: GTX 970
Guest GPU: GTX 760
Host Kernel version: 4.14.3-1-ARCH
Host QEMU version: 2.10.1

When using the looking-glass-client in -F fullscreen mode on a multi-monitor host setup; the mouse min/max boundaries will drift when switching between client and host. A temporary fix for this might be to have an option on the client to eat all mouse input until a hotkey is pressed. Similar to how virt-viewer / virt-manager works if you fullscreen. Requiring shift+f6 or the control+alt key to be pressed.

**Comment by gnif** [comment] 2017-12-15 05:01
This only occurs if your client is not running at the guest's native resolution, work needs to be done to the mouse scaling code, for now though its low priority. I would rather this fixed then adding a workaround.

**Comment by r4m0n** [comment] 2017-12-15 05:10
Unless you can add code to grab the mouse on the client if the mouse is grabbed on the host (which I don't think there's an easy way to detect), I think an option to manually grab the mouse/keyboard on the client is quite useful, or the mouse WILL escape the client eventually (and usually very fast).

**Comment by gnif** [comment] 2017-12-15 05:33
Just hit `Scroll Lock` to capture the cursor to the screen for now, like I said, it's low priority and I won't be spending time on this just yet.

**Comment by gnif** [comment] 2017-12-15 08:18
I just realized what the problem is... Windows has mouse acceleration!
Give this a go: http://donewmouseaccel.blogspot.com.au/2010/03/markc-windows-7-mouse-acceleration-fix.html

Once windows is running 1:1 you will get perfect sync.

**Comment by r4m0n** [comment] 2017-12-15 14:31
Good find on the scaling thing, now the mouse is syncing perfectly! And thanks for the tip with ScrollLock, hadn't noticed it in the code before.

**Comment by gnif** [comment] 2017-12-15 20:18
Closing as fixed, thanks for confirming.

**Closed by gnif** 2017-12-15 20:18 UTC
Labels: low-priority-bug

**Comment by icewind1991** [comment] 2018-01-12 18:39
This should probably be added to the documentation as it's a major cause of headaches and the cause isn't apparent

**Comment by gnif** [comment] 2018-01-13 07:56
It was 29 days ago...

https://looking-glass.hostfission.com/node/7
