### ISSUE TITLE
Build linking error (Arch Linux)

### ISSUE THREAD

**Issue by ratking1337** [gnif/LookingGlass#243] opened 2020-02-24 16:32 UTC
### Required information

Host CPU: i7 8700k
Host GPU: RTX 2080
Guest GPU: -
Host Kernel version: 5.5.5
Host QEMU version: -
                         
make[1]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
[ 10%] Built target lg_common
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
[ 22%] Built target font_SDL
[ 22%] Built target spice
[ 24%] Built target decoders
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
[ 27%] Built target clipboard_X11
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
[ 31%] Built target fonts
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
[ 34%] Built target clipboards
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
[ 37%] Built target renderer_OpenGL
[ 84%] Built target renderer_EGL
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
[ 87%] Built target renderers
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
[ 89%] Linking C executable looking-glass-client
/usr/bin/ld: common/liblg_common.a(crash.linux.c.o): in function `lookup_address':
crash.linux.c:(.text.lookup_address+0x36): undefined reference to `bfd_get_section_flags'
/usr/bin/ld: crash.linux.c:(.text.lookup_address+0x5b): undefined reference to `bfd_get_section_size'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/looking-glass-client.dir/build.make:173: looking-glass-client] Error 1
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make[1]: *** [CMakeFiles/Makefile2:291: CMakeFiles/looking-glass-client.dir/all] Error 2
make[1]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make: *** [Makefile:130: all] Error 2

###  **FYI: I've disabled the -Werror cmake flag, because otherwise build fails on a warning:**

-- GMP libs: /usr/lib/libgmp.so /usr/lib/libgmpxx.so
-- The following features have been enabled:

 * ENABLE_OPENGL, Legacy OpenGL renderer.
 * ENABLE_EGL, EGL renderer.
 * ENABLE_CB_X11, X11 Clipboard Integration.
 * ENABLE_BACKTRACE, Backtrace support.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/feo/Git/LookingGlass/client/build
make[1]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make[2]: Entering directory '/home/feo/Git/LookingGlass/client/build'
[  1%] Building C object common/CMakeFiles/lg_common.dir/src/stringutils.c.o
[  3%] Building C object common/CMakeFiles/lg_common.dir/src/stringlist.c.o
[  5%] Building C object common/CMakeFiles/lg_common.dir/src/option.c.o
[  6%] Building C object common/CMakeFiles/lg_common.dir/src/crash.linux.c.o
/home/feo/Git/LookingGlass/common/src/crash.linux.c: In function ‘lookup_address’:
/home/feo/Git/LookingGlass/common/src/crash.linux.c:101:8: error: implicit declaration of function ‘bfd_get_section_flags’; did you mean ‘bfd_set_section_flags’? [-Werror=implicit-function-declaration]
  101 |   if ((bfd_get_section_flags(crash.fd, crash.section) & SEC_ALLOC) == 0)
      |        ^~~~~~~~~~~~~~~~~~~~~
      |        bfd_set_section_flags
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make[2]: *** [common/CMakeFiles/lg_common.dir/build.make:102: common/CMakeFiles/lg_common.dir/src/crash.linux.c.o] Error 1
make[2]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make[1]: *** [CMakeFiles/Makefile2:318: common/CMakeFiles/lg_common.dir/all] Error 2
make[1]: Leaving directory '/home/feo/Git/LookingGlass/client/build'
make: *** [Makefile:130: all] Error 2

The same happens on both master branch and Aur package. Tested on two different machines, both running Arch.

**Comment by gnif** [comment] 2020-02-24 21:23
Duplicate of #232

**Closed by gnif** 2020-02-24 21:23 UTC
