### ISSUE TITLE
Mouse cursor jumping all over the screen

### ISSUE THREAD

**Issue by thejavascriptman** [gnif/LookingGlass#315] opened 2020-10-19 05:20 UTC
### Problem Description

On recent LG versions mouse cursor jumps all over the screen  when using Spice, this issue is not present on B2-rc4, but happens on B2 and master.

Steps to reproduce:
* Install LG host and client (B2 or master version)
* Configure the Windows guest to use display scaling above 100% (tested with 150% and 200%)
* The issue seems to happen 30% of the time when ran via the terminal, and 90% of the time when launched by using a desktop shortcut (the issue is completely fixed if if enable mouse capture by pressing Scroll Lock)

Desktop shortcut
```
[Desktop Entry]
Comment=
Exec=looking-glass-client win:fullScreen=yes win:noScreensaver=yes spice:port=5920
Name=LG Test
NoDisplay=false
Path[$e]=
StartupNotify=true
Terminal=0
TerminalOptions=
Type=Application
X-KDE-SubstituteUID=false
X-KDE-Username=
```

### Logs

Client Log:

```
$ looking-glass-client win:fullScreen=yes win:noScreensaver=yes spice:port=5920
177415018737 [I]               main.c:1675 | main                           | Looking Glass (B2-rc4-11-g8692e9af80+1)
177415018759 [I]               main.c:1676 | main                           | Locking Method: Atomic
177415128400 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
177415151205 [I]                egl.c:188  | egl_initialize                 | Double buffering is off
177415167632 [I]                egl.c:202  | egl_initialize                 | Multisampling enabled, max samples: 4
177415167641 [I]               main.c:1101 | try_renderer                   | Using Renderer: EGL
177415202040 [I]               main.c:1428 | lg_run                         | Using Clipboard: X11
177415205155 [I]                egl.c:405  | egl_render_startup             | Supported extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
177415205169 [I]                egl.c:411  | egl_render_startup             | use native: false
177415240777 [I]                egl.c:500  | egl_render_startup             | Vendor  : X.Org
177415240786 [I]                egl.c:501  | egl_render_startup             | Renderer: Radeon RX 590 Series (POLARIS10, DRM 3.35.0, 5.4.71-1-lts, LLVM 10.0.1)
177415240788 [I]                egl.c:502  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 20.1.5
177415446157 [I]               main.c:1559 | lg_run                         | Host ready, reported version: B2-0-g76710ef201
177415446173 [I]               main.c:1560 | lg_run                         | Starting session
177473980419 [I]               main.c:844  | eventFilter                    | Quit event received, exiting...
```

Host Log:

```
 36199020186 [I]               dxgi.c:390  | dxgi_init                      | Device Descripion: NVIDIA GeForce RTX 2070
 36199020593 [I]               dxgi.c:391  | dxgi_init                      | Device Vendor ID : 0x10de
 36199020925 [I]               dxgi.c:392  | dxgi_init                      | Device Device ID : 0x1f02
 36199021257 [I]               dxgi.c:393  | dxgi_init                      | Device Video Mem : 8031 MiB
 36199021596 [I]               dxgi.c:394  | dxgi_init                      | Device Sys Mem   : 0 MiB
 36199021931 [I]               dxgi.c:395  | dxgi_init                      | Shared Sys Mem   : 8190 MiB
 36199022272 [I]               dxgi.c:396  | dxgi_init                      | Feature Level    : 0xb100
 36199022606 [I]               dxgi.c:397  | dxgi_init                      | Capture Size     : 3840 x 2160
 36199022961 [I]               dxgi.c:398  | dxgi_init                      | AcquireLock      : enabled
 36199047335 [I]               dxgi.c:520  | dxgi_init                      | Source Format    : DXGI_FORMAT_B8G8R8A8_UNORM
 36199048431 [I]                app.c:260  | captureStart                   | Capture Size     : 31 MiB (33177600)
 36199048891 [I]                app.c:262  | captureStart                   | ==== [ Capture  Start ] ====
 36199054851 [I]                app.c:114  | frameThread                    | Frame thread started
```

**Comment by gnif** [comment] 2020-10-19 05:23
`Looking Glass (B2-rc4-11-g8692e9af80+1)`
`Host ready, reported version: B2-0-g76710ef201`

Please be sure you're running the right versions.

**Comment by thejavascriptman** [comment] 2020-10-19 05:34
Sorry for the wrong log, I just installed the latest versions from master, and the issue is still present

```
181517642849 [I]               main.c:1740 | main                           | Looking Glass (9d0ae23f9f+)
181517642874 [I]               main.c:1741 | main                           | Locking Method: Atomic
181517730140 [I]            ivshmem.c:181  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
181517752171 [I]                egl.c:188  | egl_initialize                 | Double buffering is off
181517768514 [I]                egl.c:202  | egl_initialize                 | Multisampling enabled, max samples: 4
181517768525 [I]               main.c:1142 | try_renderer                   | Using Renderer: EGL
181517800680 [I]               main.c:1493 | lg_run                         | Using Clipboard: X11
181517802372 [I]                egl.c:403  | egl_render_startup             | Supported extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
181517802385 [I]                egl.c:409  | egl_render_startup             | use native: false
181517841605 [I]                egl.c:498  | egl_render_startup             | Vendor  : X.Org
181517841616 [I]                egl.c:499  | egl_render_startup             | Renderer: Radeon RX 590 Series (POLARIS10, DRM 3.35.0, 5.4.71-1-lts, LLVM 10.0.1)
181517841620 [I]                egl.c:500  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 20.1.5
181518045960 [I]               main.c:1624 | lg_run                         | Host ready, reported version: B2-26-g9d0ae23f9f
181518045974 [I]               main.c:1625 | lg_run                         | Starting session
181518220487 [I]               main.c:486  | frameThread                    | Format: FRAME_TYPE_BGRA 3840x2160 3840 15360
181524177416 [I]               main.c:1010 | eventFilter                    | Server Mode: on
181554309312 [I]               main.c:1010 | eventFilter                    | Server Mode: off
```

```
 40301643987 [I]               dxgi.c:393  | dxgi_init                      | Device Descripion: NVIDIA GeForce RTX 2070
 40301644450 [I]               dxgi.c:394  | dxgi_init                      | Device Vendor ID : 0x10de
 40301644854 [I]               dxgi.c:395  | dxgi_init                      | Device Device ID : 0x1f02
 40301645294 [I]               dxgi.c:396  | dxgi_init                      | Device Video Mem : 8031 MiB
 40301645654 [I]               dxgi.c:397  | dxgi_init                      | Device Sys Mem   : 0 MiB
 40301646004 [I]               dxgi.c:398  | dxgi_init                      | Shared Sys Mem   : 8190 MiB
 40301646388 [I]               dxgi.c:399  | dxgi_init                      | Feature Level    : 0xb100
 40301646740 [I]               dxgi.c:400  | dxgi_init                      | Capture Size     : 3840 x 2160
 40301647108 [I]               dxgi.c:401  | dxgi_init                      | AcquireLock      : enabled
 40301660068 [I]               dxgi.c:524  | dxgi_init                      | Source Format    : DXGI_FORMAT_B8G8R8A8_UNORM
 40301662323 [I]                app.c:263  | captureStart                   | Capture Size     : 31 MiB (33177600)
 40301662833 [I]                app.c:265  | captureStart                   | ==== [ Capture  Start ] ====
 40301663482 [I]                app.c:115  | frameThread                    | Frame thread started
```

**Comment by gnif** [comment] 2020-10-19 05:36
Is this Xorg or Wayland? What DM?

**Comment by thejavascriptman** [comment] 2020-10-19 05:37
* Xorg
* KDE Plasma 5.20
* Host: ArchLinux with kernel 5.4.71-1-lts
* Guest: Windows 10 2004

**Comment by gnif** [comment] 2020-10-19 05:38
Can you please be certain that B2-rc4 was OK? There have been no spice/mouse changes between B2 and B2-rc4.

**Comment by thejavascriptman** [comment] 2020-10-19 05:56
B2-rc4 seems to be working fine.

I obtained the B2-rc4 host from the Looking Glass website and built the client using 969effedde74ca42feed26228820ff85983f9037

```
182635601286 [I]               main.c:1646 | main                           | Looking Glass (B2-rc3-33-gdc4d1d49fa+1)
182635601310 [I]               main.c:1647 | main                           | Locking Method: Atomic
182635669948 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
182635704378 [I]                egl.c:188  | egl_initialize                 | Double buffering is off
182635720873 [I]                egl.c:202  | egl_initialize                 | Multisampling enabled, max samples: 4
182635720885 [I]               main.c:1074 | try_renderer                   | Using Renderer: EGL
182635755607 [I]               main.c:1399 | lg_run                         | Using Clipboard: X11
182635757545 [I]                egl.c:405  | egl_render_startup             | Supported extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
182635757560 [I]                egl.c:411  | egl_render_startup             | use native: false
182635793513 [I]                egl.c:500  | egl_render_startup             | Vendor  : X.Org
182635793522 [I]                egl.c:501  | egl_render_startup             | Renderer: Radeon RX 590 Series (POLARIS10, DRM 3.35.0, 5.4.71-1-lts, LLVM 10.0.1)
182635793526 [I]                egl.c:502  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 20.1.5
182635999985 [I]               main.c:1530 | lg_run                         | Host ready, reported version: B2-rc4-0-g969effedde
182636000011 [I]               main.c:1531 | lg_run                         | Starting session
182653151657 [I]               main.c:819  | eventFilter                    | Quit event received, exiting...
```

**Comment by thejavascriptman** [comment] 2020-10-19 06:44
Found the commit responsible of this behavior: 5c912e3c27af7f1034f96b93c63753fcbf8c120b (the commit before that one is working fine)

Log
```
185910259930 [I]               main.c:1660 | main                           | Looking Glass (B2-rc4-6-g7e362050f7+1)
185910259963 [I]               main.c:1661 | main                           | Locking Method: Atomic
185910355315 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
185910374578 [I]                egl.c:188  | egl_initialize                 | Double buffering is off
185910408157 [I]                egl.c:202  | egl_initialize                 | Multisampling enabled, max samples: 4
185910408169 [I]               main.c:1088 | try_renderer                   | Using Renderer: EGL
185910449310 [I]               main.c:1413 | lg_run                         | Using Clipboard: X11
185910451770 [I]                egl.c:405  | egl_render_startup             | Supported extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
185910451784 [I]                egl.c:411  | egl_render_startup             | use native: false
185910489847 [I]                egl.c:500  | egl_render_startup             | Vendor  : X.Org
185910489857 [I]                egl.c:501  | egl_render_startup             | Renderer: Radeon RX 590 Series (POLARIS10, DRM 3.35.0, 5.4.71-1-lts, LLVM 10.0.1)
185910489859 [I]                egl.c:502  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 20.1.5
185910694601 [I]               main.c:1544 | lg_run                         | Host ready, reported version: B2-rc4-6-g7e362050f7+1
185910694615 [I]               main.c:1545 | lg_run                         | Starting session
185916639059 [I]               main.c:831  | eventFilter                    | Quit event received, exiting...
```

**Comment by daiaji** [comment] 2020-11-07 12:37
11117370717 [I]               main.c:1675 | main                           | Looking Glass (B2-0-g76710ef201)
 11117370744 [I]               main.c:1676 | main                           | Locking Method: Atomic
 11117450102 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
 11117493552 [I]                egl.c:188  | egl_initialize                 | Double buffering is off
 11117510547 [I]                egl.c:202  | egl_initialize                 | Multisampling enabled, max samples: 4
 11117510558 [I]               main.c:1101 | try_renderer                   | Using Renderer: EGL
 11117525328 [I]               main.c:1428 | lg_run                         | Using Clipboard: X11
 11117526693 [I]                egl.c:405  | egl_render_startup             | Supported extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
 11117526707 [I]                egl.c:411  | egl_render_startup             | use native: false
 11117541808 [I]                egl.c:500  | egl_render_startup             | Vendor  : X.Org
 11117541818 [I]                egl.c:501  | egl_render_startup             | Renderer: Radeon RX 550 Series (POLARIS11, DRM 3.38.0, 5.8.18-1-MANJARO, LLVM 10.0.1)
 11117541821 [I]                egl.c:502  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 20.2.1
 11117749519 [I]               main.c:1559 | lg_run                         | Host ready, reported version: B2-0-g76710ef201
 11117749539 [I]               main.c:1560 | lg_run                         | Starting session
 11129503457 [I]               main.c:969  | eventFilter                    | Server Mode: on
 11132571127 [I]               main.c:969  | eventFilter                    | Server Mode: off
``
I reproduced the problem。
But it seems that after I switch mouse capture mode, my mouse won't dance.

**Comment by notepass** [comment] 2020-11-08 21:26
It seems like this problem is related to mouse acceleration in the windows guest. After disabling mouse acceleration I can use the client again without mouse capture.
(This was tested on B2:)
` 14301956983 [I]               main.c:1675 | main                           | Looking Glass (B2-rc4-11-g8692e9af80+1)
 14301957006 [I]               main.c:1676 | main                           | Locking Method: Atomic
 14302032416 [I]            ivshmem.c:180  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
 14302084490 [I]                egl.c:188  | egl_initialize                 | Double buffering is off
 14302098118 [I]                egl.c:202  | egl_initialize                 | Multisampling enabled, max samples: 4
 14302098137 [I]               main.c:1101 | try_renderer                   | Using Renderer: EGL
 14302113669 [I]               main.c:1428 | lg_run                         | Using Clipboard: X11
 14302116029 [I]                egl.c:405  | egl_render_startup             | Supported extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
 14302116041 [I]                egl.c:411  | egl_render_startup             | use native: false
 14302125232 [I]                egl.c:500  | egl_render_startup             | Vendor  : X.Org
 14302125243 [I]                egl.c:501  | egl_render_startup             | Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.38.0, 5.8.18-1-MANJARO, LLVM 10.0.1)
 14302125247 [I]                egl.c:502  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 20.2.1
 14302333608 [I]               main.c:1559 | lg_run                         | Host ready, reported version: B2-0-g76710ef201
 14302333620 [I]               main.c:1560 | lg_run                         | Starting session
 14436055993 [I]               main.c:969  | eventFilter                    | Server Mode: on
 14436648470 [I]               main.c:969  | eventFilter                    | Server Mode: off
`

**Comment by gnif** [comment] 2020-11-10 09:12
@notepass this is documented on the wiki.

All others, a fix went in last night that hopefully should help, can you all update and re-test please?

**Comment by daiaji** [comment] 2020-11-10 10:42
@gnif   
```
 468008017 [I]               main.c:1789 | main                           | Looking Glass (B2-55-gcd4dfd7252)
   468008043 [I]               main.c:1790 | main                           | Locking Method: Atomic
   468091065 [I]            ivshmem.c:121  | ivshmemOpenDev                 | KVMFR Device     : /dev/shm/looking-glass
   468154878 [I]                egl.c:196  | egl_initialize                 | Double buffering is off
   468183056 [I]                egl.c:210  | egl_initialize                 | Multisampling enabled, max samples: 4
   468183066 [I]               main.c:1191 | try_renderer                   | Using Renderer: EGL
   468209686 [I]               main.c:1542 | lg_run                         | Using Clipboard: X11
   468211833 [I]                egl.c:431  | egl_render_startup             | use native: false
   468234386 [I]                egl.c:522  | egl_render_startup             | EGL       : 1.5
   468234395 [I]                egl.c:523  | egl_render_startup             | Vendor    : X.Org
   468234398 [I]                egl.c:524  | egl_render_startup             | Renderer  : Radeon RX 550 Series (POLARIS11, DRM 3.38.0, 5.8.18-1-MANJARO, LLVM 10.0.1)
   468234404 [I]                egl.c:525  | egl_render_startup             | Version   : OpenGL ES 3.2 Mesa 20.2.1
   468234409 [I]                egl.c:526  | egl_render_startup             | EGL APIs  : OpenGL OpenGL_ES 
   468234413 [I]                egl.c:527  | egl_render_startup             | Extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_CHROMIUM_sync_control EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_swap_buffers_with_damage EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_KHR_swap_buffers_with_damage EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_NOK_texture_from_pixmap EGL_WL_bind_wayland_display 
   468444174 [I]               main.c:1673 | lg_run                         | Host ready, reported version: B2-55-gcd4dfd7252
   468444187 [I]               main.c:1674 | lg_run                         | Starting session
   468745779 [I]               main.c:1710 | lg_run                         | Waiting for the host to restart...
   468745791 [I]               main.c:1673 | lg_run                         | Host ready, reported version: B2-55-gcd4dfd7252
   468745794 [I]               main.c:1674 | lg_run                         | Starting session
   469047270 [I]               main.c:1710 | lg_run                         | Waiting for the host to restart...
   470046381 [I]               main.c:1673 | lg_run                         | Host ready, reported version: B2-55-gcd4dfd7252
   470046394 [I]               main.c:1674 | lg_run                         | Starting session
   470246921 [I]               main.c:1710 | lg_run                         | Waiting for the host to restart...
   470246935 [I]               main.c:1673 | lg_run                         | Host ready, reported version: B2-55-gcd4dfd7252
   470246941 [I]               main.c:1674 | lg_run                         | Starting session
   470647275 [I]               main.c:1710 | lg_run                         | Waiting for the host to restart...
   471647240 [I]               main.c:1673 | lg_run                         | Host ready, reported version: B2-55-gcd4dfd7252
   471647254 [I]               main.c:1674 | lg_run                         | Starting session
   471848296 [I]               main.c:1710 | lg_run                         | Waiting for the host to restart...
   471848309 [I]               main.c:1673 | lg_run                         | Host ready, reported version: B2-55-gcd4dfd7252
   471848311 [I]               main.c:1674 | lg_run                         | Starting session
   472148924 [I]               main.c:1710 | lg_run                         | Waiting for the host to restart...
   473148732 [I]               main.c:1673 | lg_run                         | Host ready, reported version: B2-55-gcd4dfd7252
   473148750 [I]               main.c:1674 | lg_run                         | Starting session
   473448326 [I]               main.c:1710 | lg_run                         | Waiting for the host to restart...
   473448335 [I]               main.c:1673 | lg_run                         | Host ready, reported version: B2-55-gcd4dfd7252
   473448337 [I]               main.c:1674 | lg_run                         | Starting session
   473748655 [I]               main.c:1710 | lg_run                         | Waiting for the host to restart...
   474558601 [I]               main.c:934  | eventFilter                    | Quit event received, exiting...
```
Lookingglass doesn't work for me.

**Comment by gnif** [comment] 2020-11-10 10:54
Bleeding edge increases the required amount of RAM, increase your ivshmem size to the next power of two

**Comment by daiaji** [comment] 2020-11-10 11:22
@gnif There seems to be no perceptible bug.

**Comment by thejavascriptman** [comment] 2020-11-10 14:28
@gnif thank you for the fix, just tested b942085e6c635c68dc0cd7bccfc134621c0f948c and it now works much better. However there are some minor issues that may be related to my resolution (3840x2160) or display scaling (200%):
* When LG client is launched, the cursor will still jump all around until you move the mouse in circles for a few seconds
* Large cursors go crazy when approaching window borders i.e. when you want to resize a window, this time the cursor only jumps about 50px around (default cursor size does not have this problem)

**Comment by gnif** [comment] 2020-11-10 14:44
@thejavascriptman I have also noted the large cursor issue and I am investigating a fix

**Comment by daiaji** [comment] 2020-11-11 10:28
> Turn off Enhance pointer precision to disable mouse acceleration.

@thejavascriptman It works for me. How about trying it?😋

**Comment by gnif** [comment] 2020-11-11 12:22
Please don't pollute this issue with tutorials, the instructions on how to perform this are on the wiki:
https://looking-glass.io/wiki/FAQ#The_mouse_doesn.27t_stay_aligned_with_the_host.

**Comment by gnif** [comment] 2020-12-04 09:10
The mouse code has been revamped over the last few days and seems to be working well, can you please confirm if this issue is fixed?

**Comment by w23** [comment] 2020-12-09 07:34
Can add a data point that updating to the latest master seems to have fixed the issue for me.

**Comment by thejavascriptman** [comment] 2020-12-13 02:57
@gnif, I'm unable to check if the mouse issue is fixed because LG client always captures the mouse, tried toggling `spice:captureOnStart` and manually pressing SrcLk they have no effect.

Tested on latest master (5802bfb5eb19e62b42c3e4bb4c70745b262220fa) and the latest commit from 2020-12-04 (80d911f040b68fdd33afb5ec149f8016b4698cc6).

**Comment by gnif** [comment] 2020-12-13 02:59
LG should only be holding the mouse if the application in the guest is. Is this occurring on the windows desktop?

**Comment by thejavascriptman** [comment] 2020-12-13 04:17
Yes, I just have Chrome and Steam open with no games running

**Comment by gnif** [comment] 2020-12-13 04:18
What is your Window Manager, and are you using Wayland or Xorg?

**Comment by thejavascriptman** [comment] 2020-12-13 04:22
KDE on Xorg

**Comment by gnif** [comment] 2020-12-13 04:29
Thanks, KDE has been reported several times now to have this issue, I will try to replicate it when I get some time and get back to you :)

**Comment by gnif** [comment] 2021-01-06 13:22
This issue has been resolved in the latest master build of LG, please be sure to update both the host and the client.

**Closed by gnif** 2021-01-06 13:22 UTC
