### ISSUE TITLE
Cursor does not hide in some games

### ISSUE THREAD

**Issue by cmdrkotori** [gnif/LookingGlass#90] opened 2018-08-05 10:39 UTC
### Required information

Host CPU: AMD FX(tm)-8320 Eight-Core Processor
Host GPU: [AMD/ATI] Curacao XT / Trinidad XT [Radeon R7 370 / R9 270X/370X]
Guest GPU: [AMD/ATI] Cape Verde PRO [Radeon HD 7750/8740 / R7 250E]
Host Kernel version: 4.17.6
Host QEMU version: 2.12.0
Version: Using git master on host and client.
Applications that are known to cause this issue: Tomb Raider Legend/Anniversary/Underworld

When running either of the listed games, the cursor hides on the attached monitor but not on the looking-glass window. For the entirety of the application's runtime, Looking-glass shows whatever the mouse cursor was when it was hidden at the location of where it was hidden.

![screenshot_20180805_203601](https://user-images.githubusercontent.com/11322485/43685053-3f0e4050-98ef-11e8-912b-0c48d58e48a8.png)

**Comment by gnif** [comment] 2018-08-05 14:04
I will need a copy of one of these games to test and diagnose.

**Comment by daiaji** [comment] 2018-08-24 16:54
@gnif Is it illegal to use these copies (non-DRM) in the laws of your country?
I may be able to provide you with a copy of non-DRM.

**Comment by 0x0aa** [comment] 2018-11-22 04:47
@cmdrkotori @gnif Tomb Raider: Anniversary has a demo version available, is this reproducable on it? The full games are currently also on sale on Steam for pennies.

**Comment by daiaji** [comment] 2018-11-23 15:41
The atmosphere has become very awkward.😏

**Comment by gnif** [comment] 2019-01-02 00:43
I finally managed to check this, it seems that this issue has been fixed since this was opened as I can not reproduce it. Can you please confirm?

**Comment by gnif** [comment] 2019-01-02 00:58
Closing unless confirmed this is still an issue.

**Closed by gnif** 2019-01-02 00:58 UTC

**Comment by cmdrkotori** [comment] 2019-01-02 04:34
I can confirm that this is fixed.
