### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by gitthail** [gnif/LookingGlass#255] opened 2020-03-22 16:42 UTC
### Required information
<pre>[  1%] <font color="#00AA00">Building C object common/CMakeFiles/lg_common.dir/src/crash.linux.c.o</font>
<b>/home/blahblah/scratch/LookingGlass-Release-B1/common/src/crash.linux.c:</b> In function ‘<b>lookup_address</b>’:
<b>/home/blahblah/scratch/LookingGlass-Release-B1/common/src/crash.linux.c:101:8:</b> <font color="#AA0000"><b>error: </b></font>implicit declaration of function ‘<b>bfd_get_section_flags</b>’; did you mean ‘<b>bfd_set_section_flags</b>’? [<font color="#AA0000"><b>-Werror=implicit-function-declaration</b></font>]
  101 |   if ((<font color="#AA0000"><b>bfd_get_section_flags</b></font>(crash.fd, crash.section) &amp; SEC_ALLOC) == 0)
      |        <font color="#AA0000"><b>^~~~~~~~~~~~~~~~~~~~~</b></font>
      |        <font color="#00AA00">bfd_set_section_flags</font>
compilation terminated due to -Wfatal-errors.
</pre>

Host CPU: i7-9800k
Host GPU: rtx2080
Guest GPU: not relevant
Host Kernel version: 5.4.24-1-MANJARO
Host QEMU version: not relevant

**Comment by gnif** [comment] 2020-03-22 23:27
Duplicate of #232

**Closed by gnif** 2020-03-22 23:27 UTC
