### ISSUE TITLE
Icon is missing for the client window - no desktop file provided

### ISSUE THREAD

**Issue by Ashark** [gnif/LookingGlass#1049] opened 2022-11-26 18:38 UTC
In Wayland on KDE when you start the looking glass client, you see the generic wayland icon instead of looking glass icon.
I use Arch Linux and installed looking-glass-client-git. In this package there is currently no any file besides the binary.
In Wayland the icon is set by matching the application against its .desktop file and reading its Icon= field.

I did it locally, and it worked.
Create a file `~/.local/share/applications/looking-glass-client.desktop` with the following content:
```
[Desktop Entry]
Name=Looking Glass
Comment=A client application for accessing the LookingGlass IVSHMEM device of a VM
Exec=looking-glass-client
Icon=looking-glass-client
Terminal=false
Type=Application
Categories=Utility;Viewer;RemoteAccess;ParallelComputing;
```

Copy the icon from resources https://github.com/gnif/LookingGlass/blob/master/resources/icon-128x128.png to `~/.local/share/icons/hicolor/128x128/apps/looking-glass-client.png`

Make the window rule in kde: desktop file - force - looking-glass-client.

Now the window has nice looking glass icon and is easily recognizable in the taskbar.

I think if you provide a desktop file, package maintainers can easily place it to the package. Not sure if window rule also should be packaged.
P.S. I filled Categories from this list: https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry

**Comment by gnif** [comment] 2022-11-26 18:46
Duplicate of PR 1011

**Closed by gnif** 2022-11-26 18:46 UTC
